plugins {
    id 'com.android.application'
}

android {
    namespace 'com.luanarabelo.treinodaluana.v12.wear'
    compileSdk 36

    defaultConfig {
        applicationId 'com.luanarabelo.treinodaluana.v12'
        minSdk 30
        targetSdk 35
        versionCode 12
        versionName '12.0-watch8'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
