plugins {
    id 'com.android.application'
}

android {
    namespace 'com.luanarabelo.treinodaluana.v7'
    compileSdk 35

    defaultConfig {
        applicationId 'com.luanarabelo.treinodaluana.v7'
        minSdk 26
        targetSdk 35
        versionCode 7
        versionName '7.0'
    }

    compileOptions {
        sourceCompatibility JavaVersion.VERSION_17
        targetCompatibility JavaVersion.VERSION_17
    }
}
